# Generated by Django 4.2 on 2023-04-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='inventary',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='propmotions',
            new_name='promotions',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
    ]
