# Generated by Django 4.2 on 2023-04-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_inventary_products_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='customer',
        ),
    ]
