# Generated by Django 4.2 on 2023-04-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_order_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
